name: Test Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run my GitHub action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # organization and repository will default to the current context